# Search Agent Configuration

name: search
description: Retrieves product information using RAG (Retrieval-Augmented Generation)
version: 1.0.0

# Azure AI Search settings
ai_search:
  index_name: smartproof-product-info
  query_type: semantic
  top_results: 10
  min_relevance_score: 0.5

# GPT settings for query enhancement
gpt:
  model: gpt-4
  max_tokens: 500
  temperature: 0.2
